runtime: nodejs16

instance_class: F1
service: proton3dviewer
handlers:
  - url: /favicon.ico
    static_files: dist/favicon.ico
    upload: dist/favicon.ico

  - url: /logo.png
    static_files: dist/logo.png
    upload: dist/logo.png
  
  - url: /
    secure: always
    static_files: dist/index.html
    upload: dist/index.html