runtime: nodejs16

instance_class: F1
service: proton3dviewer
basic_scaling:
  max_instances: 1
  idle_timeout: 5m
handlers:
  - url: /assets
    static_dir: dist/assets

  - url: .*
    static_files: dist/index.html
    upload: dist/index.html
