runtime: nodejs16

instance_class: F1
service: proton3dviewer
basic_scaling:
  max_instances: automatic
  idle_timeout: 5m
handlers:
  - url: .*
    static_files: dist/index.html
    upload: dist/index.html

  - url: /assets
    static_files: dist/assets
