version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - static_files:/app/dist
    ports:
      - '8080:8080'

  proxy:
    image: nginx:mainline
    build:
      context: .
    ports:
      - '3000:80'
    volumes:
      - static_files:/usr/share/nginx/html
      - ./proxy/default.conf:/etc/nginx/templates/default.conf.template
    depends_on:
      - app

volumes:
  static_files:
