# GCP App Engine CI/CD workflow for GitHub
# Actions; deploys app to Google Cloud and
# performs a cURL to ensure the web app is
# live without build errors
#
# CREDIT: https://medium.com/geekculture/deploy-to-google-app-engine-using-github-actions-ci-cd-f25d4c965fbc
name: Proton-AppEngine-Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ secrets.PROTON_PROJECT_ID }}
        credentials: ${{ secrets.GCP_APP_ENGINE_CREDENTIALS }}

    - name: cURL Web App
      run: curl "${{ steps.deploy.outputs.url }}"
